# Generated by Django 4.2.7 on 2025-08-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Full name for company ID generation', max_length=100, null=True),
        ),
    ]
