# Generated by Django 4.2.7 on 2025-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='company_name',
            field=models.CharField(default='Default Company', help_text='Company this plan is assigned to', max_length=100),
        ),
    ]
