# Generated by Django 4.2.7 on 2025-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20250901_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='custom_features',
            field=models.JSONField(blank=True, help_text='Additional features for custom plans', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Whether this is a custom plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('custom', 'Custom'), ('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=50),
        ),
    ]
