# Generated by Django 4.2.7 on 2025-08-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_plan_userplanassignment_alter_user_plan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userplanassignment',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userplanassignment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='plan',
            name='max_agents',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of agents allowed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userplanassignment',
            name='notes',
            field=models.TextField(blank=True, help_text='Reason for status change'),
        ),
        migrations.AddField(
            model_name='userplanassignment',
            name='previous_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userplanassignment'),
        ),
        migrations.AddField(
            model_name='userplanassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('upgraded', 'Upgraded')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='company_name',
        ),
    ]
