# Generated by Django 4.2.7 on 2025-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_plan_unique_together_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
