# Generated by Django 4.2.7 on 2025-08-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_plan_plan_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
