# Generated by Django 4.2.7 on 2025-09-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_plan_expiry_date'),
    ]

    operations = [
    ]
