# Generated by Django 4.2.7 on 2025-08-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_agent_company_id'),
        ('chatbot', '0005_chatbotconfiguration_userprofile_is_favorite'),
        ('human_handoff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('initial_message', models.TextField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True, null=True)),
                ('company_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_sessions', to='admin_dashboard.agent')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_sessions', to='chatbot.userprofile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
