# Generated by Django 4.2.7 on 2025-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='profile_collection_state',
            field=models.CharField(choices=[('name', 'Collecting Name'), ('country_code', 'Collecting Country Code'), ('phone', 'Collecting Phone'), ('email', 'Collecting Email'), ('address', 'Collecting Address'), ('complete', 'Profile Complete')], default='name', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='temp_profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
