# Generated by Django 4.2.7 on 2025-08-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_profile_collection_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='company_id',
            field=models.CharField(default='DEFAULT_COMPANY', help_text='Company ID for multi-tenant isolation', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='company_id',
            field=models.CharField(default='DEFAULT_COMPANY', help_text='Company ID for multi-tenant isolation', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_id',
            field=models.CharField(default='DEFAULT_COMPANY', help_text='Company ID for multi-tenant isolation', max_length=20),
        ),
    ]
