# Generated by Django 4.2.7 on 2025-08-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatmessage_attachments_alter_chatmessage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(help_text='Company ID for chatbot configuration', max_length=20, unique=True)),
                ('primary_color', models.CharField(default='#f7941d', help_text='Primary color for chatbot (hex format)', max_length=7)),
                ('secondary_color', models.CharField(default='#652d90', help_text='Secondary color for chatbot (hex format)', max_length=7)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left'), ('top-right', 'Top Right'), ('top-left', 'Top Left')], default='bottom-right', max_length=20)),
                ('iframe_width', models.IntegerField(default=400, help_text='Width of chatbot iframe in pixels')),
                ('iframe_height', models.IntegerField(default=600, help_text='Height of chatbot iframe in pixels')),
                ('welcome_message', models.TextField(default='Hello! How can I help you today?', help_text='Initial welcome message')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('enable_file_upload', models.BooleanField(default=True)),
                ('enable_voice_messages', models.BooleanField(default=False)),
                ('enable_typing_indicator', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite to prevent deletion during clear operations'),
        ),
    ]
