# Generated by Django 4.2.7 on 2025-08-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_plan_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.CharField(blank=True, help_text='Unique company identifier for chatbot integration', max_length=20, null=True, unique=True),
        ),
    ]
