# Generated by Django 4.2.7 on 2025-09-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_plan_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Plan expiry date', null=True),
        ),
    ]
