# Generated by Django 4.2.7 on 2025-09-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_plan_custom_features_plan_is_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('upgraded', 'Upgraded')], default='active', max_length=20),
        ),
    ]
