# Generated by Django 4.2.7 on 2025-09-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_userplanassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True, help_text='True if admin needs to set their own password on first login'),
        ),
    ]
