# Generated by Django 4.2.7 on 2025-09-02 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dashboard', '0003_alter_agent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(help_text='Company ID requesting the upgrade', max_length=20)),
                ('company_name', models.CharField(help_text='Company name for display', max_length=200)),
                ('current_plan', models.CharField(help_text='Current plan name', max_length=50)),
                ('requested_plan', models.CharField(help_text='Requested plan name', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Reason for upgrade request', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from reviewer', null=True)),
                ('requested_by', models.ForeignKey(help_text='Admin user who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Superadmin user who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Upgrade Request',
                'verbose_name_plural': 'Plan Upgrade Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
