# Generated by Django 4.2.7 on 2025-08-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company_id',
            field=models.CharField(blank=True, help_text='Company ID of the admin who created this agent', max_length=20, null=True),
        ),
    ]
