# Generated by Django 4.2.7 on 2025-08-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_add_company_id_to_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='chat_messages', to='chatbot.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
