# Generated by Django 4.2.7 on 2025-08-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatbotconfiguration_userprofile_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by_agent',
            field=models.BooleanField(default=False, help_text='True if uploaded by agent, False if uploaded by user'),
        ),
    ]
