# Generated by Django 4.2.7 on 2025-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_plan_features_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyplan',
            name='custom_max_agents',
            field=models.IntegerField(blank=True, help_text='Custom max agents for Custom plan', null=True),
        ),
        migrations.AddField(
            model_name='companyplan',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom price for Custom plan', max_digits=10, null=True),
        ),
    ]
