# Generated by Django 4.2.7 on 2025-09-04 01:15

import chatbot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_uploadedfile_uploaded_by_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('uploader', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=16)),
                ('file', models.FileField(upload_to=chatbot.models.chat_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=127)),
                ('size', models.BigIntegerField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'session_id'], name='chatbot_cha_company_d00d55_idx'), models.Index(fields=['created_at'], name='chatbot_cha_created_d49b1a_idx')],
            },
        ),
    ]
