# Generated by Django 4.2.7 on 2025-09-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_plan_planupgraderequest_planfeature_companyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features_line',
            field=models.CharField(default='AI-powered Chatbot', max_length=200),
        ),
    ]
